package me.predatorray.jdbc.datasource;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Queue;
import java.util.concurrent.ConcurrentLinkedQueue;

/**
 *
 */
public class CloseOnCompletionCallableStatement
        extends CallableStatementProxy {

    private final Queue<ResultSet> resultSetsToBeClosed;

    /**
     * Construct a CloseOnCompletionCallableStatement with a existing
     * callableStatement instance which will be delegate
     * by this object.
     * @param callableStatement the delegated callableStatement instance
     */
    public CloseOnCompletionCallableStatement(
            CallableStatement callableStatement) {
        super(callableStatement);
        resultSetsToBeClosed = new ConcurrentLinkedQueue<ResultSet>();
    }

    @Override
    public ResultSet executeQuery() throws SQLException {
        ResultSet resultSetToBeClosed = super.executeQuery();
        resultSetsToBeClosed.add(resultSetToBeClosed);
        return resultSetToBeClosed;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        ResultSet resultSetToBeClosed = super.executeQuery(sql);
        resultSetsToBeClosed.add(resultSetToBeClosed);
        return resultSetToBeClosed;
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        ResultSet resultSetToBeClosed = super.getResultSet();
        resultSetsToBeClosed.add(resultSetToBeClosed);
        return resultSetToBeClosed;
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        ResultSet resultSetToBeClosed = super.getGeneratedKeys();
        resultSetsToBeClosed.add(resultSetToBeClosed);
        return resultSetToBeClosed;
    }

    /**
     * Since this CallableStatement is will be closed when all its dependent
     * result sets are closed,
     * it will always return true.
     * @return true (always)
     */
    @Override
    public boolean isCloseOnCompletion() {
        return true;
    }

    /**
     * Release this CallableStatement's database, and at the same time close
     * all the ResultSet instances which was
     * generated by this object.
     * @throws SQLException
     */
    @Override
    public void close() throws SQLException {
        try {
            for (ResultSet resultSetToBeClosed : resultSetsToBeClosed) {
                if (!resultSetToBeClosed.isClosed()) {
                    resultSetToBeClosed.close();
                }
            }
        } finally {
            super.close();
        }
    }

    /**
     * When this CallableStatement instance is released by GC, {@link #close()}
     * will be called automatically to ensure that all connections and
     * resources to the database have been safely closed.
     * @throws Throwable
     */
    @Override
    protected void finalize() throws Throwable {
        try {
            if (!isClosed()) {
                this.close();
            }
        } finally {
            super.finalize();
        }
    }
}
